### ISSUE TITLE
Infinitely resizing grid

### ISSUE THREAD

**Issue by yorrd** [vpusher/the-grid#10]
You've talked about this in the other thread. Basically, we'd have an option whether the grid should be expanding automatically or not. If it should, the grid will respond dynamically in size when adding, moving or resizing children. If not, the behavior right now is kept. 

Pull request coming soon...

**Comment by yorrd** [comment]
actually, coming right now. Have a look whether you like it this way: https://github.com/vpusher/the-grid/pull/11

**Comment by JosefJezek** [comment]
Do you plan responsive layout?

**Comment by yorrd** [comment]
@JosefJezek i have yet to write the rest of the pull reqeust. Have a look, @vpusher wanted some changes i havent come around to implementing. If you want, fork my fork and finish the pull request. Otherwise, wait for me to get it done, which I cant promise this week

**Comment by vpusher** [comment]
@JosefJezek actually, you can already make it responsive since you can bind its `cell-width`, `col-count`, ... attributes depending on whatever you want: events, media queries, ... I will add a responsive demo in the next release so you can use it.

**Comment by yorrd** [comment]
@all, I have finalized the pull request, waiting for approval
@vpusher I found it hard to do that from the outside, and somewhat unreliable. Excited to see your demo though, maybe I just missed something

**Comment by vpusher** [comment]
@JosefJezek here is the responsive sample: [demo/responsive.html](/vpusher/the-grid/blob/master/demo/responsive.html)

**Comment by vpusher** [comment]
Delivered in [v1.2.0](/vpusher/the-grid/releases/tag/v1.2.0). Enjoy.
