### ISSUE TITLE
Min/Max Width/Height for the Tiles

### ISSUE THREAD

**Issue by DarkSideOfMo0n** [vpusher/the-grid#12]
@vpusher This Component is awsome.
I think a good feature would be if the size of the Tiles or Children can be restricted. Like setting it to a max width of 4 and a minimum of 2.

Thanks and Greetings
Pascal Laier

**Comment by vpusher** [comment]
@PascalLaier Hey, thanks ! It seems doable easily. I will look into it.

**Comment by vpusher** [comment]
@PascalLaier released in [v1.0.3](/vpusher/the-grid/releases/tag/v1.3.0). Enjoy 😀

**Comment by DarkSideOfMo0n** [comment]
@vpusher Thx very much!
