### ISSUE TITLE
Listening for change events

### ISSUE THREAD

**Issue by lamplightdev** [vpusher/the-grid#15]
Hi,

I want to do something (e.g. persist the current grid layout) after a tile has been moved/resized. Is there a way to do this currently, or would the element need to be updated to fire an event on tile changes, which a containing element could then listen for?

Thanks,
Chris.

**Comment by vpusher** [comment]
Thanks for feedback @lamplightdev. Definitely doable and useful. I will add it in the next release.

**Comment by yorrd** [comment]
@lamplightdev @vpusher you can add an observer on the databinding on the property and do whatever you want to do there

**Comment by lamplightdev** [comment]
@yorrd @vpusher thanks for the tip. I'm using polymer-redux however using only one-way data binding so an observer wouldn't work in this case without adding some extra properties to track the tile properties and observing them to then update my redux state which I'd rather avoid

**Comment by vpusher** [comment]
@lamplightdev are the following events enough for you:
* `resize` (once the tile gripper is released `~touchend/mouseup`)
* `move` (once the tile is released `~touchend/mouseup`)
?
with the updated tile in the event detail

**Comment by lamplightdev** [comment]
@vpusher yes, those would be ideal, thanks!

**Comment by vpusher** [comment]
Delivered in [v1.2.0](/vpusher/the-grid/releases/tag/v1.2.0). Enjoy.
