### ISSUE TITLE
Save the state of the grid

### ISSUE THREAD

**Issue by mohanzeal** [vpusher/the-grid#19]
Could you please explain how can we save the state of the grid layout once the elements are moved and also are nesting the grid elements allowed?

**Comment by vpusher** [comment]
We probably need some `serialization()` method here, that would extract the each attribute of the tiles and return them as JSON. If I happen to find some time, I will think about it but feel free to PR for a quick solution 😜

**Comment by syu93** [comment]
You can listen for the both event emited by each tile on **move** and **resize** and serialize the new positions from the tile object contained in the detail of the event

**Comment by vpusher** [comment]
@mohanzeal delivered in [v1.4.0](https://github.com/vpusher/the-grid/releases/tag/v1.4.0)
