### ISSUE TITLE
Nesting inside another component doesn't work

### ISSUE THREAD

**Issue by bkjohnson** [vpusher/the-grid#2]
I've started building an Electron + Polymer app and the tile elements inside the grid don't appear to work if the grid is nested inside another component.

Here `the-grid` works as expected, and you can see that the proper classes are applied to the `div`.

![image](https://cloud.githubusercontent.com/assets/2008881/24829865/e346ef74-1c3f-11e7-9906-f519c3431072.png)

But when it is nested inside `my-app` the tile divs don't have the proper styles applied. 

![screenshot from 2017-04-08 09-48-44](https://cloud.githubusercontent.com/assets/2008881/24829908/b18dd4c4-1c40-11e7-8fec-b738837f0858.png)

I added a `console.log(style.textContext)` [here](https://github.com/vpusher/the-grid/blob/master/the-grid.html#L264) and the styles are definitely there so I'm not sure why they aren't being applied.  

It may not be obvious from the screenshots, but if I drag a tile the placeholder doesn't update behind it either, it just stays in the top left.

I'd be happy to submit a PR if I could tell what was causing this, but this is my first time using Polymer 2.0 (I've been using 1.x for a long time) and so I just don't really know why this is happening.  Any help would be appreciated.

**Comment by vpusher** [comment]
@bkjohnson yes, the generated stylesheet is applied for grid used as light dom because local dom can't be styled from the document (i.e. outside of the component itself). I will have a look into this. Thank you for you feedback and your PR.
