### ISSUE TITLE
Responsive grid

### ISSUE THREAD

**Issue by RemiLelaidier** [vpusher/the-grid#22]
When the-grid will be responsive ?

**Comment by vpusher** [comment]
@RemiLelaidier Responsiveness means a lot. This is often the client app which is responsible for implementing the responsive behaviour. The component is only a tool to achieve such a behaviour. Can you explain what you are expecting ?

In the meantime you have one example in [/vpusher/the-grid/blob/master/demo/responsive.html](/vpusher/the-grid/blob/master/demo/responsive.html)

**Comment by vpusher** [comment]
Feel free to re-open if you consider the component is missing something so you can implement you responsive behavior.
