### ISSUE TITLE
Set resize options tru attributes

### ISSUE THREAD

**Issue by Stefdv** [vpusher/the-grid#28]
Hey, great component 👍 
My issue is more a cosmetic request...
Would it be possible to set resize options through attibutes instead of having to add all those spans?
I would suggest to use 'corners' to add handlers to all corners
```
<tile corners></tile>
```
But anyaway...tx for the component

**Comment by vpusher** [comment]
@Stefdv, the `resize` attribute have to be set on the element that handles the grab, so you can define and design your own grabbers/grippers. There is no "default" grippers.

Consequently, `<tile corners></tile>` would have no effect. It is up to you to add them as tile children. That's the purpose of the feature.
