### ISSUE TITLE
Demo on webcomponents.org isn't showing up

### ISSUE THREAD

**Issue by yorrd** [vpusher/the-grid#5]
Hey, thanks for the component. 

I see you have coded a proper demo. Unfortunately it's not showing up on the webcomponents.org page, so it's not of much use for someone looking for the right component.

Thanks and have a good day

EDIT: I should clarify: this is only about the button in the left sidebar, the demo in the middle works just fine :)

**Comment by vpusher** [comment]
Thx for feedback.

Yeah, I know, It seems the documentation system and webcomponents.org are not ready yet with Polymer 2 syntax and specificities. I know that some bunch of work are being done on that topic so we can be able to document properly our components based on Polymer 2.

We probably need to wait for [Polymer analyzer](https://github.com/Polymer/polymer-analyzer) v2.0.0 GA for this to be fixed.
