### ISSUE TITLE
Drag doesn't work in dom-repeat

### ISSUE THREAD

**Issue by yorrd** [vpusher/the-grid#6]
I'm filling the grid automatically from a database. As soon as I'm using a dom-repeat instead of directly putting the children into the grid, dragging stops working. When I have both hard-coded children and ones in a dom-repeat, those from the dom-repeat don't work, the hard-coded ones do though.

```
        <the-grid draggable resizable animated col-count="{{maxCol}}" row-count="{{maxRow}}" cell-margin="0" cell-height="200" cell-width="200">
<!-- WORKS -->
            <div class="tile" col="0" row="0" height="1" width="4">test
            </div>
<!-- DOESN'T WORK -->
            <template is="dom-repeat" items="{{conBoxes}}" as="box">
                <div class="tile" col$="{{box.col}}" row$="{{box.row}}" height$="{{box.height}}" width$="{{box.width}}">
                    {{box.title}}
                </div>
            </template>
            <div placeholder></div>
        </the-grid>
```

oh and by the way, I'm not sure your last example from the demo would work (the one with the emojis), because that's basically the same as what I'm trying to do

EDIT: resizable doesn't work either, same conditions

**Comment by vpusher** [comment]
@yorrd look at #7 and tell me if it fixes your use case.

**Comment by yorrd** [comment]
@vpusher it does. Actually works pretty perfectly

Now another issue I have is with nesting grids and then dragging. But that's just a design issue of my own and can probably be fixed by `e.preventDefault()`. What do you think?

**Comment by vpusher** [comment]
@yorrd Some bunch of code would help a bit to understand your problem 🙂

**Comment by yorrd** [comment]
@vpusher sure. I'll open another issue though, that's unrelated :) gimme a second

You go ahead and close this issue whenever you please - maybe you want to keep it open till this is on the main branch, idk :)
