### ISSUE TITLE
Drop Events

### ISSUE THREAD

**Issue by yorrd** [vpusher/the-grid#9]
Hi, it's me again :smile: 

For this one, I'd be willing to write a pull request as well since it's not exactly a small fix. Let me know if you want me to do it or rather want to work on it yourself.

I'm using this to represent a database and of course, the changes need to be reflected back into storage. So it'd be an amazing feature to have an event which basically tells you which tile has been moved (as a DOM element for example) and where it is now. This would allow me to listen to this kind of event and update my database items accordingly. 

Thanks and have a great day

**Comment by yorrd** [comment]
Well, I'm not thinking reactively. You can just use the property for width, height, col and row as a double-data binding

**Comment by vpusher** [comment]
A dedicated event for this seems a good idea since you may not have (or could not) used binding.
